# Generated by Django 2.0 on 2017-12-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CollegePrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.CharField(max_length=1000)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RjSite.College')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=100)),
                ('filePath', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('coments', models.CharField(max_length=1000)),
                ('prompts', models.ManyToManyField(to='RjSite.CollegePrompt')),
            ],
            options={
                'ordering': ('-time', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('usr_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RjSite.Usr')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
            bases=('RjSite.usr',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usr_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RjSite.Usr')),
                ('colleges', models.ManyToManyField(to='RjSite.College')),
                ('studentParent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RjSite.Parent')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
            bases=('RjSite.usr',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('usr_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RjSite.Usr')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
            bases=('RjSite.usr',),
        ),
        migrations.AddField(
            model_name='mail',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_receiver', to='RjSite.Usr'),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_sender', to='RjSite.Usr'),
        ),
        migrations.AddField(
            model_name='studentessay',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RjSite.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='studentTeacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RjSite.Teacher'),
        ),
        migrations.AddField(
            model_name='bill',
            name='billingParent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RjSite.Parent'),
        ),
        migrations.AddField(
            model_name='bill',
            name='billingTeacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RjSite.Teacher'),
        ),
    ]
