# Generated by Django 2.0 on 2018-01-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RjSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentessay',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
