# Generated by Django 2.0 on 2017-12-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CollegePrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.CharField(max_length=1000)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollageApp.College')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StudentEssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=100)),
                ('filePath', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('coments', models.CharField(max_length=1000)),
                ('prompts', models.ManyToManyField(to='CollageApp.CollegePrompt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Student')),
            ],
            options={
                'ordering': ('-time', 'title', 'id'),
            },
        ),
    ]
